version: 2

updates:
  - package-ecosystem: cargo
    schedule:
      interval: monthly
    directories:
      - /
      - /acme
      - /core
      - /engine
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
