[package]
build = "build.rs"
description = "the engine of the acme platform enabling automation and orchestration of tasks across various sources and sinks"
name = "acme-engine"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = false
features = ["default"]
rustc-args = ["--cfg", "docsrs"]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "v{{version}}"

[lib]
bench = false

[dependencies]
# local
acme-core = { workspace = true }
# async
tokio = { features = ["sync"], optional = true, workspace = true }
# concurrency & parallelism
crossbeam = { optional = true, workspace = true }
rayon = { optional = true, workspace = true }
# data-structures
bytes = { optional = true, workspace = true }
dashmap = { optional = true, workspace = true }
# serialization
serde = { features = ["derive"], optional = true, workspace = true }
serde_derive = { optional = true, workspace = true }
serde_json = { optional = true, workspace = true }
# error handling
anyhow = { optional = true, workspace = true }
thiserror = { workspace = true }
# macros
paste = { workspace = true }
smart-default = { workspace = true }
strum = { features = ["derive"], workspace = true }
# random
getrandom = { optional = true, workspace = true }
rand = { optional = true, workspace = true }
rand_distr = { optional = true, workspace = true }
# time
chrono = { optional = true, workspace = true }
time = { optional = true, workspace = true }
# tracing
tracing = { optional = true, workspace = true }
# wasm
wasm-bindgen = { optional = true, workspace = true }

[dev-dependencies]
lazy_static = { workspace = true }

[features]
default = [
  "std",
]

full = [
  "default",
  "anyhow",
  "bytes",
  "json",
  "serde",
  "time",
  "tokio",
  "tracing",
]

# ************* [FF:Features] *************

json = [
  "alloc",
  "serde",
  "serde_json",
  "acme-core/json",
]

nightly = [
  "acme-core/nightly",
]

time = [
  "alloc",
  "chrono",
  "time_1",
]

# ************* [FF:Environments] *************
std = [
  "alloc",
  "acme-core/std",
  "anyhow/std",
  "getrandom?/std",
  "rand?/std",
  "rand?/std_rng",
  "rand_distr?/std",
  "serde?/std",
  "serde_json?/std",
  "strum/std",
  "thiserror/std",
  "time?/std",
  "wasm-bindgen?/std",
]

wasi = [
  "acme-core/wasi",
]

wasm = [
  "wasm_bindgen",
  "acme-core/wasm",
  "chrono?/wasmbind",
  "getrandom?/wasm_js",
  "time?/wasm-bindgen",
]

# ************* [FF:Dependencies] *************
alloc = [
  "acme-core/alloc",
  "rand?/alloc",
  "rand_distr?/alloc",
  "serde?/alloc",
  "serde_json?/alloc",
  "time?/alloc",
  "wasm-bindgen?/gg-alloc",
]


bytes = [
  "dep:bytes",
  "tokio?/bytes",
]

chrono = [
  "dep:chrono",
  "acme-core/chrono",
  "std",
]

crossbeam = ["dep:crossbeam"]

dashmap = ["dep:dashmap"]

rand = [
  "dep:rand",
  "dep:rand_distr",
  "rng",
  "acme-core/rand",
  "time?/rand",
]

rayon = ["dep:rayon"]

rng = [
  "dep:getrandom",
  "acme-core/rng",
  "rand?/os_rng",
  "rand?/small_rng",
]

serde = [
  "dep:serde",
  "dep:serde_derive",
  "acme-core/serde",
  "rand?/serde",
  "rand_distr?/serde",
  "time?/serde",
]

serde_json = [
  "dep:serde_json",
  "acme-core/serde_json",
]

time_1 = [
  "dep:time",
  "acme-core/time_1",
]

tokio = ["dep:tokio"]

tracing = [
  "dep:tracing",
  "acme-core/tracing",
  "tokio?/tracing",
]

uuid = [
  "acme-core/uuid",
  "rng",
]

wasm_bindgen = [
  "dep:wasm-bindgen",
  "acme-core/wasm_bindgen",
]
