name: cargo-publish

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  repository_dispatch:
    types: [crates-io, cargo-publish]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

permissions:
  contents: read
  deployments: write

jobs:
  crates-io:
    runs-on: ubuntu-latest
    environment: 
      name: crates-io
      url: https://crates.io/crates/${{ matrix.package }}
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        package:
          # sdk
          - pzzld-core
          - pzzld
          # components
          - pzzld-basic-cmp
          - pzzld-plant
          - pzzld-worker
          # binaries
          - pzzld-node
          - pzzld-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.ref || github.ref }}
          repository: ${{ github.event.client_payload.repository || github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Publish (${{ matrix.package }})
        run: cargo publish --locked --package ${{ matrix.package }}
