name: Clippy

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
    branches:
      - main
      - $default-branch
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
      - $default-branch
    tags:
      - v*.*.*
      - "*-nightly"
  release:
    types: [ created, edited ]
  repository_dispatch:
    types: [ clippy, cargo-clippy ]
  workflow_dispatch:

jobs:
  clippy:
    runs-on: ubuntu-latest
    permissions:
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      contents: read
      security-events: write
      statuses: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          components: clippy, rustfmt
          toolchain: nightly
          override: true
      -
        name: Setup the for sarif output
        run: cargo install clippy-sarif sarif-fmt
      -
        name: Run Clippy
        run:
          cargo clippy
          --all-features
          --workspace
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
      -
        name: Upload analysis
        uses: github/codeql-action/upload-sarif@v3
        continue-on-error: true
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
