name: crates-io

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  CARGO_TERM_COLOR: always
  CARGO_PACKAGE_NAME: ${{ github.event.inputs.package_name || github.event.repository.name }}
  RUST_BACKTRACE: full
  RUST_LOG: acme=debug,info

on:
  push:
    tags: [ v*, "*-nightly" ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: read
  packages: write

jobs:
  features:
    env:
      PACKAGE_PREFIX: ${{ github.event.inputs.package_name || github.event.repository.name }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        feature: [ core, ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - 
        name: rustup
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - 
        name: cache
        uses: Swatinem/rust-cache@v2
      - 
        name: publish (${{ matrix.feature }})
        run: cargo publish --all-features -v -p ${{ env.PACKAGE_PREFIX }}-${{ matrix.feature }}
  root:
    needs: [features]
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: rustup
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
      - 
        name: cache
        uses: Swatinem/rust-cache@v2
      - 
        name: Publish (root)
        run: cargo publish --package ${{ github.event.repository.name }} --all-features
