name: rust

concurrency:   
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUST_LOG: acme=debug,info

on:
  pull_request:
    branches: [ main, master, ]
    types: [ opened, synchronize, reopened ]
  push:
    tags: [ v*, "*-nightly" ]
  repository_dispatch:
    types: [ rust ]
  workflow_dispatch:

permissions: 
  contents: read
  deployments: read
  packages: write

jobs:
  workspace:
    strategy:
      fail-fast: false
      matrix:
        os:  [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: setup rustup
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          cache-workspaces: true
      - 
        name: setup cache
        uses: Swatinem/rust-cache@v2
      - 
        name: build
        run: cargo build -r -v --workspace --all-features
      - 
        name: test
        run: cargo test -r -v --workspace --all-features
      - 
        name: bench
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: cargo bench -v --workspace --features full
